// 3세(만 3세 전후) 아이와의 일상 영어 대화를 위한 문장 DB
// 하루에 3문장씩, 날짜(연중 일수) 기준으로 순환 사용됩니다.
// 새 세트를 배열 뒤에 추가하면 자동으로 순환 주기에 포함됩니다.
// pron: 한글로 표기한 영어 발음(읽는 법) 입니다.

const sentences = [
  { theme: "아침 인사", tip: "눈뜨자마자 매일 같은 말로 인사해주면 아이가 자연스럽게 따라 해요.",
    sentences: [
      { english: "Good morning!", pron: "굿모닝!", korean: "좋은 아침이에요!" },
      { english: "Did you sleep well?", pron: "디쥬 슬립 웰?", korean: "잘 잤어요?" },
      { english: "Let's get up now.", pron: "렛츠 겟 업 나우.", korean: "이제 일어나요." },
    ] },
  { theme: "아침밥", tip: "밥 먹기 전후로 반복해서 말해주세요.",
    sentences: [
      { english: "Let's eat breakfast.", pron: "렛츠 잇 브렉퍼스트.", korean: "아침 먹자." },
      { english: "I'm hungry.", pron: "아임 헝그리.", korean: "나 배고파." },
      { english: "This is yummy!", pron: "디스 이즈 야미!", korean: "이거 맛있어!" },
    ] },
  { theme: "양치질", tip: "칫솔질하는 동안 신나게 말해주면 좋아해요.",
    sentences: [
      { english: "Brush your teeth.", pron: "브러쉬 유어 티쓰.", korean: "이 닦자." },
      { english: "Open your mouth.", pron: "오픈 유어 마우쓰.", korean: "입 벌려봐." },
      { english: "Good job, all done!", pron: "굿 잡, 올 던!", korean: "잘했어, 다 했다!" },
    ] },
  { theme: "옷 입기", tip: "옷을 고를 때 선택지를 주며 말해보세요.",
    sentences: [
      { english: "Let's get dressed.", pron: "렛츠 겟 드레스트.", korean: "옷 입자." },
      { english: "Put on your shirt.", pron: "풋 온 유어 셔츠.", korean: "셔츠 입어봐." },
      { english: "You look so cute!", pron: "유 룩 쏘 큐트!", korean: "너 정말 귀엽다!" },
    ] },
  { theme: "신발 신기", tip: "현관에서 나갈 준비할 때 쓰기 좋아요.",
    sentences: [
      { english: "Put on your shoes.", pron: "풋 온 유어 슈즈.", korean: "신발 신자." },
      { english: "Which shoes do you like?", pron: "위치 슈즈 두 유 라익?", korean: "어떤 신발이 좋아?" },
      { english: "Let's go outside!", pron: "렛츠 고 아웃사이드!", korean: "밖에 나가자!" },
    ] },
  { theme: "놀이터", tip: "놀이터에서 신나는 톤으로 말해주세요.",
    sentences: [
      { english: "Let's go to the playground.", pron: "렛츠 고 투 더 플레이그라운드.", korean: "놀이터에 가자." },
      { english: "I want to swing.", pron: "아이 원트 투 스윙.", korean: "나 그네 타고 싶어." },
      { english: "Be careful, okay?", pron: "비 케어풀, 오케이?", korean: "조심해, 알았지?" },
    ] },
  { theme: "공놀이", tip: "공을 주고받으며 말해보세요.",
    sentences: [
      { english: "Let's play with the ball.", pron: "렛츠 플레이 위드 더 볼.", korean: "공 가지고 놀자." },
      { english: "Catch the ball!", pron: "캐치 더 볼!", korean: "공 잡아!" },
      { english: "Nice throw!", pron: "나이스 쓰로우!", korean: "잘 던졌어!" },
    ] },
  { theme: "색깔", tip: "주변 물건 색을 가리키며 질문해보세요.",
    sentences: [
      { english: "What color is this?", pron: "왓 컬러 이즈 디스?", korean: "이건 무슨 색이야?" },
      { english: "I like the color red.", pron: "아이 라익 더 컬러 레드.", korean: "나는 빨간색이 좋아." },
      { english: "The sky is blue.", pron: "더 스카이 이즈 블루.", korean: "하늘은 파란색이야." },
    ] },
  { theme: "숫자 세기", tip: "계단을 오르내릴 때 같이 세어보세요.",
    sentences: [
      { english: "Let's count together.", pron: "렛츠 카운트 투게더.", korean: "같이 세어보자." },
      { english: "One, two, three!", pron: "원, 투, 쓰리!", korean: "하나, 둘, 셋!" },
      { english: "How many do you see?", pron: "하우 매니 두 유 씨?", korean: "몇 개 보여?" },
    ] },
  { theme: "동물 - 강아지", tip: "강아지를 보면 손가락으로 가리키며 말해보세요.",
    sentences: [
      { english: "Look, a dog!", pron: "룩, 어 도그!", korean: "봐봐, 강아지야!" },
      { english: "The dog is cute.", pron: "더 도그 이즈 큐트.", korean: "강아지가 귀여워." },
      { english: "Woof woof, says the dog.", pron: "우프 우프, 세즈 더 도그.", korean: "멍멍, 강아지가 그래." },
    ] },
  { theme: "동물 - 고양이", tip: "동물 소리를 흉내 내며 말하면 더 재밌어해요.",
    sentences: [
      { english: "The cat is sleeping.", pron: "더 캣 이즈 슬리핑.", korean: "고양이가 자고 있어." },
      { english: "Can I pet the cat?", pron: "캔 아이 펫 더 캣?", korean: "고양이 만져도 돼?" },
      { english: "Meow, says the cat.", pron: "미야우, 세즈 더 캣.", korean: "야옹, 고양이가 그래." },
    ] },
  { theme: "날씨 - 맑음", tip: "창밖을 보며 오늘의 날씨를 이야기해보세요.",
    sentences: [
      { english: "It's sunny today.", pron: "잇츠 써니 투데이.", korean: "오늘 날씨가 맑아." },
      { english: "Let's wear a hat.", pron: "렛츠 웨어 어 햇.", korean: "모자 쓰자." },
      { english: "The sun is bright.", pron: "더 썬 이즈 브라이트.", korean: "해가 밝아." },
    ] },
  { theme: "날씨 - 비", tip: "비 오는 날 창밖을 보며 말해보세요.",
    sentences: [
      { english: "It's raining outside.", pron: "잇츠 레이닝 아웃사이드.", korean: "밖에 비가 와." },
      { english: "Let's take an umbrella.", pron: "렛츠 테이크 언 엄브렐라.", korean: "우산 가져가자." },
      { english: "I love rainy days.", pron: "아이 러브 레이니 데이즈.", korean: "나는 비 오는 날이 좋아." },
    ] },
  { theme: "목욕 시간", tip: "물놀이하듯 즐겁게 말해주세요.",
    sentences: [
      { english: "It's bath time!", pron: "잇츠 배쓰 타임!", korean: "목욕 시간이야!" },
      { english: "The water feels warm.", pron: "더 워터 필즈 웜.", korean: "물이 따뜻해." },
      { english: "Let's wash your hair.", pron: "렛츠 워시 유어 헤어.", korean: "머리 감자." },
    ] },
  { theme: "손 씻기", tip: "밥 먹기 전, 외출 후에 반복해주세요.",
    sentences: [
      { english: "Wash your hands, please.", pron: "워시 유어 핸즈, 플리즈.", korean: "손 씻어줘." },
      { english: "Use soap and water.", pron: "유즈 소프 앤 워터.", korean: "비누랑 물을 써." },
      { english: "Now your hands are clean.", pron: "나우 유어 핸즈 아 클린.", korean: "이제 손이 깨끗해." },
    ] },
  { theme: "정리하기", tip: "놀이 후 정리 습관을 만들 때 써보세요.",
    sentences: [
      { english: "Let's clean up the toys.", pron: "렛츠 클린 업 더 토이즈.", korean: "장난감 정리하자." },
      { english: "Put it back, please.", pron: "풋 잇 백, 플리즈.", korean: "제자리에 놓아줘." },
      { english: "Great job cleaning up!", pron: "그레잇 잡 클리닝 업!", korean: "정리 잘했어!" },
    ] },
  { theme: "감정 - 행복", tip: "아이가 웃을 때 함께 말해보세요.",
    sentences: [
      { english: "I am happy!", pron: "아이 앰 해피!", korean: "나는 행복해!" },
      { english: "You make me smile.", pron: "유 메이크 미 스마일.", korean: "너 때문에 웃음이 나." },
      { english: "Let's do a happy dance!", pron: "렛츠 두 어 해피 댄스!", korean: "신나는 춤 추자!" },
    ] },
  { theme: "감정 - 슬픔", tip: "아이 감정을 먼저 읽어주는 말이에요.",
    sentences: [
      { english: "Are you sad?", pron: "아 유 새드?", korean: "슬퍼?" },
      { english: "It's okay to cry.", pron: "잇츠 오케이 투 크라이.", korean: "울어도 괜찮아." },
      { english: "I'm here for you.", pron: "아임 히어 포 유.", korean: "내가 옆에 있을게." },
    ] },
  { theme: "감정 - 화남", tip: "감정을 진정시킬 때 천천히 말해주세요.",
    sentences: [
      { english: "Are you angry?", pron: "아 유 앵그리?", korean: "화났어?" },
      { english: "Let's take a deep breath.", pron: "렛츠 테이크 어 딥 브레쓰.", korean: "숨 크게 쉬어보자." },
      { english: "It's okay, calm down.", pron: "잇츠 오케이, 캄 다운.", korean: "괜찮아, 진정해." },
    ] },
  { theme: "가족 - 엄마", tip: "엄마와의 애착 표현에 좋아요.",
    sentences: [
      { english: "I love you, Mom.", pron: "아이 러브 유, 맘.", korean: "엄마 사랑해요." },
      { english: "Where is Mommy?", pron: "웨어 이즈 마미?", korean: "엄마 어디 있어?" },
      { english: "Mommy, hug me please.", pron: "마미, 허그 미 플리즈.", korean: "엄마, 안아줘." },
    ] },
  { theme: "가족 - 아빠", tip: "아빠가 퇴근했을 때 써보세요.",
    sentences: [
      { english: "I love you, Dad.", pron: "아이 러브 유, 대드.", korean: "아빠 사랑해요." },
      { english: "Daddy is home!", pron: "대디 이즈 홈!", korean: "아빠 왔다!" },
      { english: "Let's play with Daddy.", pron: "렛츠 플레이 위드 대디.", korean: "아빠랑 놀자." },
    ] },
  { theme: "낮잠 시간", tip: "낮잠 전 루틴으로 사용해보세요.",
    sentences: [
      { english: "It's nap time.", pron: "잇츠 냅 타임.", korean: "낮잠 잘 시간이야." },
      { english: "Let's lie down.", pron: "렛츠 라이 다운.", korean: "누워보자." },
      { english: "Sweet dreams, sleepy head.", pron: "스윗 드림즈, 슬리피 헤드.", korean: "좋은 꿈 꿔, 잠꾸러기." },
    ] },
  { theme: "잠자리 인사", tip: "매일 밤 같은 순서로 말해주면 안정감을 줘요.",
    sentences: [
      { english: "It's time for bed.", pron: "잇츠 타임 포 베드.", korean: "잘 시간이야." },
      { english: "Good night, sleep tight.", pron: "굿나잇, 슬립 타이트.", korean: "잘 자, 좋은 꿈 꿔." },
      { english: "I love you so much.", pron: "아이 러브 유 쏘 머치.", korean: "정말 많이 사랑해." },
    ] },
  { theme: "그림책 읽기", tip: "책장을 넘기며 질문해보세요.",
    sentences: [
      { english: "Let's read a book.", pron: "렛츠 리드 어 북.", korean: "책 읽자." },
      { english: "Turn the page, please.", pron: "턴 더 페이지, 플리즈.", korean: "페이지 넘겨줘." },
      { english: "What happens next?", pron: "왓 해픈즈 넥스트?", korean: "다음에 무슨 일이 생길까?" },
    ] },
  { theme: "노래 부르기", tip: "좋아하는 동요를 같이 불러보세요.",
    sentences: [
      { english: "Let's sing a song.", pron: "렛츠 씽 어 송.", korean: "노래 부르자." },
      { english: "Sing it with me.", pron: "씽 잇 위드 미.", korean: "나랑 같이 불러." },
      { english: "That was a great song!", pron: "댓 워즈 어 그레잇 송!", korean: "노래 정말 좋았어!" },
    ] },
  { theme: "간식 시간", tip: "간식 고를 때 선택권을 주며 말해보세요.",
    sentences: [
      { english: "It's snack time.", pron: "잇츠 스낵 타임.", korean: "간식 시간이야." },
      { english: "Do you want a cookie?", pron: "두 유 원트 어 쿠키?", korean: "쿠키 먹을래?" },
      { english: "This snack is tasty.", pron: "디스 스낵 이즈 테이스티.", korean: "이 간식 맛있어." },
    ] },
  { theme: "물 마시기", tip: "물을 자주 챙겨줄 때 써보세요.",
    sentences: [
      { english: "Drink some water.", pron: "드링크 썸 워터.", korean: "물 좀 마셔." },
      { english: "Are you thirsty?", pron: "아 유 써스티?", korean: "목마르니?" },
      { english: "Here's your cup.", pron: "히어즈 유어 컵.", korean: "여기 컵 있어." },
    ] },
  { theme: "과일", tip: "과일을 먹으며 이름을 알려주세요.",
    sentences: [
      { english: "I like apples.", pron: "아이 라익 애플즈.", korean: "나는 사과가 좋아." },
      { english: "This banana is sweet.", pron: "디스 바나나 이즈 스윗.", korean: "이 바나나는 달아." },
      { english: "Do you want grapes?", pron: "두 유 원트 그레입스?", korean: "포도 먹을래?" },
    ] },
  { theme: "야채", tip: "야채를 잘 먹었을 때 칭찬해주세요.",
    sentences: [
      { english: "Eat your carrots.", pron: "잇 유어 캐럿츠.", korean: "당근 먹어." },
      { english: "Vegetables are good for you.", pron: "베지터블즈 아 굿 포 유.", korean: "야채는 몸에 좋아." },
      { english: "Try one more bite.", pron: "트라이 원 모어 바이트.", korean: "한 입만 더 먹어봐." },
    ] },
  { theme: "사랑 표현", tip: "이유 없이 자주 말해주면 좋아요.",
    sentences: [
      { english: "I love you very much.", pron: "아이 러브 유 베리 머치.", korean: "너를 정말 많이 사랑해." },
      { english: "You are my sunshine.", pron: "유 아 마이 선샤인.", korean: "너는 나의 햇살이야." },
      { english: "Give me a hug.", pron: "기브 미 어 허그.", korean: "안아줘." },
    ] },
  { theme: "칭찬하기", tip: "작은 성취에도 아낌없이 칭찬해주세요.",
    sentences: [
      { english: "Good job, sweetie!", pron: "굿 잡, 스위티!", korean: "잘했어, 아가!" },
      { english: "I'm so proud of you.", pron: "아임 쏘 프라우드 오브 유.", korean: "네가 정말 자랑스러워." },
      { english: "You did it!", pron: "유 디드 잇!", korean: "네가 해냈어!" },
    ] },
  { theme: "도와주세요", tip: "도움을 요청하는 표현을 알려줄 때 써보세요.",
    sentences: [
      { english: "Can you help me?", pron: "캔 유 헬프 미?", korean: "나 도와줄 수 있어?" },
      { english: "I need your help.", pron: "아이 니드 유어 헬프.", korean: "네 도움이 필요해." },
      { english: "Thank you for helping.", pron: "땡큐 포 헬핑.", korean: "도와줘서 고마워." },
    ] },
  { theme: "부탁 표현", tip: "부탁할 때 예의 표현을 자연스럽게 알려주세요.",
    sentences: [
      { english: "Please, may I have this?", pron: "플리즈, 메이 아이 해브 디스?", korean: "이거 가져도 될까요?" },
      { english: "Say please.", pron: "세이 플리즈.", korean: "'please'라고 말해봐." },
      { english: "Please and thank you.", pron: "플리즈 앤 땡큐.", korean: "부탁해요, 그리고 고마워요." },
    ] },
  { theme: "감사 표현", tip: "고마움을 표현하는 습관을 길러주세요.",
    sentences: [
      { english: "Thank you so much.", pron: "땡큐 쏘 머치.", korean: "정말 고마워." },
      { english: "You're welcome.", pron: "유어 웰컴.", korean: "천만에." },
      { english: "Say thank you.", pron: "세이 땡큐.", korean: "고맙다고 말해봐." },
    ] },
  { theme: "사과 표현", tip: "실수했을 때 사과하는 법을 알려주세요.",
    sentences: [
      { english: "I'm sorry.", pron: "아임 쏘리.", korean: "미안해." },
      { english: "It's okay, I forgive you.", pron: "잇츠 오케이, 아이 포기브 유.", korean: "괜찮아, 용서할게." },
      { english: "Let's say sorry together.", pron: "렛츠 세이 쏘리 투게더.", korean: "같이 미안하다고 말하자." },
    ] },
  { theme: "몸 부위", tip: "몸을 만지며 이름을 말해주세요.",
    sentences: [
      { english: "Where is your nose?", pron: "웨어 이즈 유어 노즈?", korean: "코가 어디 있어?" },
      { english: "Touch your toes.", pron: "터치 유어 토우즈.", korean: "발가락 만져봐." },
      { english: "This is my hand.", pron: "디스 이즈 마이 핸드.", korean: "이건 내 손이야." },
    ] },
  { theme: "얼굴", tip: "거울을 보며 표정을 이야기해보세요.",
    sentences: [
      { english: "You have a happy face.", pron: "유 해브 어 해피 페이스.", korean: "너 행복한 얼굴이네." },
      { english: "Look at your eyes.", pron: "룩 앳 유어 아이즈.", korean: "눈을 봐봐." },
      { english: "Smile for me!", pron: "스마일 포 미!", korean: "나를 위해 웃어줘!" },
    ] },
  { theme: "산책하기", tip: "손을 잡고 걸으며 말해보세요.",
    sentences: [
      { english: "Let's take a walk.", pron: "렛츠 테이크 어 워크.", korean: "산책하자." },
      { english: "Hold my hand.", pron: "홀드 마이 핸드.", korean: "내 손 잡아." },
      { english: "Look at the trees.", pron: "룩 앳 더 트리즈.", korean: "나무를 봐봐." },
    ] },
  { theme: "자동차", tip: "차를 탈 때 안전벨트 습관과 함께 말해주세요.",
    sentences: [
      { english: "Let's get in the car.", pron: "렛츠 겟 인 더 카.", korean: "차에 타자." },
      { english: "Buckle your seatbelt.", pron: "버클 유어 씻벨트.", korean: "안전벨트 매자." },
      { english: "We are going home.", pron: "위 아 고잉 홈.", korean: "우리 집에 가고 있어." },
    ] },
  { theme: "공원 나들이", tip: "공원에서 보이는 것들을 함께 이야기해보세요.",
    sentences: [
      { english: "Let's go to the park.", pron: "렛츠 고 투 더 파크.", korean: "공원에 가자." },
      { english: "I see a duck!", pron: "아이 씨 어 덕!", korean: "오리가 보여!" },
      { english: "Let's feed the ducks.", pron: "렛츠 피드 더 덕스.", korean: "오리한테 먹이 주자." },
    ] },
  { theme: "친구와 놀기", tip: "친구를 만났을 때 쓰기 좋은 표현이에요.",
    sentences: [
      { english: "Let's play with friends.", pron: "렛츠 플레이 위드 프렌즈.", korean: "친구들이랑 놀자." },
      { english: "Can I join you?", pron: "캔 아이 조인 유?", korean: "나도 같이 해도 돼?" },
      { english: "We are having fun!", pron: "위 아 해빙 펀!", korean: "우리 재밌게 놀고 있어!" },
    ] },
  { theme: "나누기", tip: "장난감을 나눠 쓸 때 알려주세요.",
    sentences: [
      { english: "Let's share the toy.", pron: "렛츠 쉐어 더 토이.", korean: "장난감 같이 쓰자." },
      { english: "Can I have a turn?", pron: "캔 아이 해브 어 턴?", korean: "나도 한 번 해도 돼?" },
      { english: "Sharing is caring.", pron: "쉐어링 이즈 케어링.", korean: "나누는 건 배려하는 거야." },
    ] },
  { theme: "장난감", tip: "좋아하는 장난감 이름을 물어보세요.",
    sentences: [
      { english: "This is my favorite toy.", pron: "디스 이즈 마이 페이버릿 토이.", korean: "이건 내가 제일 좋아하는 장난감이야." },
      { english: "Let's play with blocks.", pron: "렛츠 플레이 위드 블록스.", korean: "블록 가지고 놀자." },
      { english: "Where is your teddy bear?", pron: "웨어 이즈 유어 테디 베어?", korean: "네 곰인형 어디 있어?" },
    ] },
  { theme: "그림 그리기", tip: "그림 그릴 때 색을 물어보며 대화해보세요.",
    sentences: [
      { english: "Let's draw a picture.", pron: "렛츠 드로우 어 픽쳐.", korean: "그림 그리자." },
      { english: "What color do you want?", pron: "왓 컬러 두 유 원트?", korean: "무슨 색 원해?" },
      { english: "That's a beautiful drawing!", pron: "댓츠 어 뷰티풀 드로잉!", korean: "정말 예쁜 그림이야!" },
    ] },
  { theme: "블록 놀이", tip: "블록을 쌓고 무너뜨리며 놀아보세요.",
    sentences: [
      { english: "Let's build a tower.", pron: "렛츠 빌드 어 타워.", korean: "탑을 만들자." },
      { english: "Stack the blocks up.", pron: "스택 더 블록스 업.", korean: "블록을 쌓아보자." },
      { english: "Oh no, it fell down!", pron: "오 노, 잇 펠 다운!", korean: "어머, 무너졌다!" },
    ] },
  { theme: "퍼즐", tip: "퍼즐 조각을 맞추며 격려해주세요.",
    sentences: [
      { english: "Let's do a puzzle.", pron: "렛츠 두 어 퍼즐.", korean: "퍼즐 하자." },
      { english: "Where does this piece go?", pron: "웨어 더즈 디스 피스 고?", korean: "이 조각 어디로 가?" },
      { english: "You finished the puzzle!", pron: "유 피니쉬드 더 퍼즐!", korean: "퍼즐 다 했어!" },
    ] },
  { theme: "크기 비교", tip: "물건 크기를 비교하며 말해보세요.",
    sentences: [
      { english: "This one is big.", pron: "디스 원 이즈 빅.", korean: "이건 커." },
      { english: "This one is small.", pron: "디스 원 이즈 스몰.", korean: "이건 작아." },
      { english: "Which one is bigger?", pron: "위치 원 이즈 비거?", korean: "어떤 게 더 커?" },
    ] },
  { theme: "모양", tip: "주변 물건에서 모양을 찾아보세요.",
    sentences: [
      { english: "This is a circle.", pron: "디스 이즈 어 서클.", korean: "이건 동그라미야." },
      { english: "Can you find a square?", pron: "캔 유 파인드 어 스퀘어?", korean: "네모 찾을 수 있어?" },
      { english: "That's a triangle.", pron: "댓츠 어 트라이앵글.", korean: "그건 세모야." },
    ] },
  { theme: "계절 - 봄", tip: "산책하며 봄 풍경을 이야기해보세요.",
    sentences: [
      { english: "Spring is here!", pron: "스프링 이즈 히어!", korean: "봄이 왔어!" },
      { english: "The flowers are blooming.", pron: "더 플라워즈 아 블루밍.", korean: "꽃이 피고 있어." },
      { english: "Let's smell the flowers.", pron: "렛츠 스멜 더 플라워즈.", korean: "꽃 냄새 맡아보자." },
    ] },
  { theme: "계절 - 여름", tip: "더운 날 물놀이와 함께 말해보세요.",
    sentences: [
      { english: "It's hot in summer.", pron: "잇츠 핫 인 서머.", korean: "여름엔 더워." },
      { english: "Let's go swimming.", pron: "렛츠 고 스위밍.", korean: "수영하러 가자." },
      { english: "I want some ice cream.", pron: "아이 원트 썸 아이스크림.", korean: "아이스크림 먹고 싶어." },
    ] },
  { theme: "계절 - 가을", tip: "낙엽을 밟으며 말해보세요.",
    sentences: [
      { english: "The leaves are falling.", pron: "더 리브즈 아 폴링.", korean: "낙엽이 떨어지고 있어." },
      { english: "It's getting cooler.", pron: "잇츠 게팅 쿨러.", korean: "날씨가 시원해지고 있어." },
      { english: "Let's jump in the leaves.", pron: "렛츠 점프 인 더 리브즈.", korean: "낙엽 위에서 점프하자." },
    ] },
  { theme: "계절 - 겨울", tip: "추운 날 옷 입히며 말해보세요.",
    sentences: [
      { english: "It's cold in winter.", pron: "잇츠 콜드 인 윈터.", korean: "겨울엔 추워." },
      { english: "Let's wear a warm coat.", pron: "렛츠 웨어 어 웜 코트.", korean: "따뜻한 외투 입자." },
      { english: "Look, it's snowing!", pron: "룩, 잇츠 스노잉!", korean: "봐봐, 눈 온다!" },
    ] },
  { theme: "동물원", tip: "동물원 나들이 전후로 써보세요.",
    sentences: [
      { english: "Let's go to the zoo.", pron: "렛츠 고 투 더 주.", korean: "동물원에 가자." },
      { english: "Look at the elephant!", pron: "룩 앳 디 엘리펀트!", korean: "코끼리 봐봐!" },
      { english: "The lion is roaring.", pron: "더 라이언 이즈 로어링.", korean: "사자가 으르렁대." },
    ] },
  { theme: "바다", tip: "바다 여행 갈 때 써보세요.",
    sentences: [
      { english: "Let's go to the beach.", pron: "렛츠 고 투 더 비치.", korean: "바다에 가자." },
      { english: "The waves are big.", pron: "더 웨이브즈 아 빅.", korean: "파도가 커." },
      { english: "Let's build a sandcastle.", pron: "렛츠 빌드 어 샌드캐슬.", korean: "모래성 만들자." },
    ] },
  { theme: "음악 듣기", tip: "음악을 틀어놓고 함께 즐겨보세요.",
    sentences: [
      { english: "Let's listen to music.", pron: "렛츠 리슨 투 뮤직.", korean: "음악 듣자." },
      { english: "Do you like this song?", pron: "두 유 라익 디스 송?", korean: "이 노래 좋아?" },
      { english: "Turn up the volume.", pron: "턴 업 더 볼륨.", korean: "소리 좀 키워줘." },
    ] },
  { theme: "춤추기", tip: "신나는 노래에 맞춰 함께 춤춰보세요.",
    sentences: [
      { english: "Let's dance together.", pron: "렛츠 댄스 투게더.", korean: "같이 춤추자." },
      { english: "Move your body!", pron: "무브 유어 바디!", korean: "몸을 움직여봐!" },
      { english: "That was so much fun.", pron: "댓 워즈 쏘 머치 펀.", korean: "정말 재미있었어." },
    ] },
  { theme: "인사 - 안녕", tip: "만나고 헤어질 때 손을 흔들며 말해보세요.",
    sentences: [
      { english: "Hello, nice to see you!", pron: "헬로우, 나이스 투 씨 유!", korean: "안녕, 만나서 반가워!" },
      { english: "Goodbye, see you later!", pron: "굿바이, 씨 유 레이터!", korean: "잘 가, 또 보자!" },
      { english: "Wave bye-bye.", pron: "웨이브 바이바이.", korean: "손 흔들어 인사해." },
    ] },
  { theme: "화장실 가기", tip: "배변 훈련 중일 때 다정하게 말해주세요.",
    sentences: [
      { english: "Do you need the potty?", pron: "두 유 니드 더 파티?", korean: "화장실 가고 싶어?" },
      { english: "Let's go to the bathroom.", pron: "렛츠 고 투 더 배쓰룸.", korean: "화장실 가자." },
      { english: "Great job going potty!", pron: "그레잇 잡 고잉 파티!", korean: "화장실 잘 갔다 왔네!" },
    ] },
  { theme: "옷 색깔 고르기", tip: "옷 고를 때 선택권을 주며 말해보세요.",
    sentences: [
      { english: "Which shirt do you want?", pron: "위치 셔츠 두 유 원트?", korean: "어떤 셔츠 입고 싶어?" },
      { english: "This one is warm.", pron: "디스 원 이즈 웜.", korean: "이건 따뜻해." },
      { english: "You picked a good one!", pron: "유 픽트 어 굿 원!", korean: "잘 골랐어!" },
    ] },
  { theme: "하루 마무리", tip: "하루를 마무리하며 오늘을 되돌아보세요.",
    sentences: [
      { english: "What a fun day!", pron: "와러 펀 데이!", korean: "정말 재미있는 하루였어!" },
      { english: "I love spending time with you.", pron: "아이 러브 스펜딩 타임 위드 유.", korean: "너랑 시간 보내는 게 좋아." },
      { english: "See you tomorrow!", pron: "씨 유 투마로우!", korean: "내일 보자!" },
    ] },
];

export default sentences;
