// 엄마와 아이가 함께 쓰는 '생활 영어' 문장 DB
// 하루에 3문장씩, 날짜(연중 일수) 기준으로 순환 사용됩니다.
// 엄마가 아이에게 말해주면서 엄마 본인도 자연스럽게 익히도록,
// 실제 일상에서 바로 쓰는 자연스러운 표현으로 구성했습니다.
// pron: 한글로 표기한 영어 발음(읽는 법) 입니다.
// 새 세트를 배열 뒤에 추가하면 자동으로 순환 주기에 포함됩니다.

const sentences = [
  { theme: "아침에 깨우기", tip: "매일 같은 말로 다정하게 깨워주면 아이가 하루를 편안하게 시작해요.",
    sentences: [
      { english: "Good morning, sweetie!", pron: "굿모닝, 스위티!", korean: "좋은 아침이야, 아가!" },
      { english: "Time to wake up.", pron: "타임 투 웨이크 업.", korean: "일어날 시간이야." },
      { english: "Did you sleep well?", pron: "디쥬 슬립 웰?", korean: "잘 잤어?" },
    ] },
  { theme: "아침 식사", tip: "먹기 전후로 반복해서 말해주면 식사 시간 표현이 자연스럽게 익어요.",
    sentences: [
      { english: "Let's have breakfast.", pron: "렛츠 해브 브렉퍼스트.", korean: "아침 먹자." },
      { english: "Are you hungry?", pron: "아 유 헝그리?", korean: "배고파?" },
      { english: "Finish your food, please.", pron: "피니쉬 유어 푸드, 플리즈.", korean: "다 먹자." },
    ] },
  { theme: "세수·양치", tip: "거울 앞에서 함께 하며 말해주면 좋아요.",
    sentences: [
      { english: "Let's brush your teeth.", pron: "렛츠 브러쉬 유어 티쓰.", korean: "이 닦자." },
      { english: "Wash your face.", pron: "워시 유어 페이스.", korean: "세수하자." },
      { english: "All clean now!", pron: "올 클린 나우!", korean: "이제 깨끗해졌다!" },
    ] },
  { theme: "옷 입기", tip: "선택지를 주며 물어보면 아이가 스스로 고르는 걸 좋아해요.",
    sentences: [
      { english: "Let's get dressed.", pron: "렛츠 겟 드레스트.", korean: "옷 입자." },
      { english: "Which one do you want?", pron: "위치 원 두 유 원트?", korean: "어떤 거 입을래?" },
      { english: "Arms up!", pron: "암즈 업!", korean: "팔 들어봐!" },
    ] },
  { theme: "어린이집 등원", tip: "나가기 전 준비 과정에서 써보세요.",
    sentences: [
      { english: "Let's get ready to go.", pron: "렛츠 겟 레디 투 고.", korean: "나갈 준비하자." },
      { english: "Put on your shoes.", pron: "풋 온 유어 슈즈.", korean: "신발 신자." },
      { english: "Don't forget your bag.", pron: "돈 포겟 유어 백.", korean: "가방 잊지 마." },
    ] },
  { theme: "헤어질 때 인사", tip: "손을 흔들며 밝게 인사하면 아이가 덜 불안해해요.",
    sentences: [
      { english: "Have a great day!", pron: "해브 어 그레잇 데이!", korean: "즐거운 하루 보내!" },
      { english: "I'll pick you up later.", pron: "아일 픽 유 업 레이터.", korean: "이따 데리러 올게." },
      { english: "Bye-bye, see you soon!", pron: "바이바이, 씨 유 쑨!", korean: "안녕, 이따 봐!" },
    ] },
  { theme: "하원·다시 만남", tip: "반갑게 안아주며 말해주세요.",
    sentences: [
      { english: "I missed you so much!", pron: "아이 미스트 유 쏘 머치!", korean: "너무 보고 싶었어!" },
      { english: "How was your day?", pron: "하우 워즈 유어 데이?", korean: "오늘 어땠어?" },
      { english: "Let's go home.", pron: "렛츠 고 홈.", korean: "집에 가자." },
    ] },
  { theme: "손 씻기·위생", tip: "밥 먹기 전, 외출 후에 반복해주세요.",
    sentences: [
      { english: "Let's wash our hands.", pron: "렛츠 워시 아워 핸즈.", korean: "손 씻자." },
      { english: "Use some soap.", pron: "유즈 썸 소프.", korean: "비누 써." },
      { english: "Now they're nice and clean.", pron: "나우 데어 나이스 앤 클린.", korean: "이제 깨끗해졌네." },
    ] },
  { theme: "간식 시간", tip: "간식을 고를 때 선택권을 주며 말해보세요.",
    sentences: [
      { english: "It's snack time.", pron: "잇츠 스낵 타임.", korean: "간식 시간이야." },
      { english: "Would you like some fruit?", pron: "우쥬 라익 썸 프룻?", korean: "과일 먹을래?" },
      { english: "Yummy, right?", pron: "야미, 라잇?", korean: "맛있지?" },
    ] },
  { theme: "물·수분 챙기기", tip: "물을 자주 챙겨줄 때 써보세요.",
    sentences: [
      { english: "Have some water.", pron: "해브 썸 워터.", korean: "물 좀 마셔." },
      { english: "Are you thirsty?", pron: "아 유 써스티?", korean: "목마르니?" },
      { english: "Take a little sip.", pron: "테이크 어 리틀 씹.", korean: "한 모금 마셔." },
    ] },
  { theme: "낮잠 시간", tip: "낮잠 전 조용한 루틴으로 사용해보세요.",
    sentences: [
      { english: "It's time for a nap.", pron: "잇츠 타임 포 어 냅.", korean: "낮잠 잘 시간이야." },
      { english: "Let's lie down.", pron: "렛츠 라이 다운.", korean: "누워보자." },
      { english: "Close your eyes.", pron: "클로즈 유어 아이즈.", korean: "눈 감아." },
    ] },
  { theme: "놀이 시작", tip: "신나는 톤으로 말하면 아이가 더 즐거워해요.",
    sentences: [
      { english: "Let's play together!", pron: "렛츠 플레이 투게더!", korean: "같이 놀자!" },
      { english: "What do you want to play?", pron: "왓 두 유 원트 투 플레이?", korean: "뭐 하고 놀까?" },
      { english: "This is so much fun!", pron: "디스 이즈 쏘 머치 펀!", korean: "정말 재밌다!" },
    ] },
  { theme: "그림 그리기", tip: "색을 물어보며 대화를 이어가 보세요.",
    sentences: [
      { english: "Let's draw a picture.", pron: "렛츠 드로우 어 픽쳐.", korean: "그림 그리자." },
      { english: "What color is this?", pron: "왓 컬러 이즈 디스?", korean: "이건 무슨 색이야?" },
      { english: "Wow, that's beautiful!", pron: "와우, 댓츠 뷰티풀!", korean: "와, 정말 예쁘다!" },
    ] },
  { theme: "블록 쌓기", tip: "쌓고 무너뜨리며 함께 놀아보세요.",
    sentences: [
      { english: "Let's build a tower.", pron: "렛츠 빌드 어 타워.", korean: "탑을 쌓자." },
      { english: "Higher and higher!", pron: "하이어 앤 하이어!", korean: "더 높이 더 높이!" },
      { english: "Oh no, it fell down!", pron: "오 노, 잇 펠 다운!", korean: "어머, 무너졌다!" },
    ] },
  { theme: "책 읽기", tip: "책장을 넘기며 질문을 던져보세요.",
    sentences: [
      { english: "Let's read a book.", pron: "렛츠 리드 어 북.", korean: "책 읽자." },
      { english: "What do you see?", pron: "왓 두 유 씨?", korean: "뭐가 보여?" },
      { english: "What happens next?", pron: "왓 해픈즈 넥스트?", korean: "다음엔 무슨 일이 생길까?" },
    ] },
  { theme: "노래·율동", tip: "좋아하는 동요를 같이 부르며 써보세요.",
    sentences: [
      { english: "Let's sing a song.", pron: "렛츠 씽 어 송.", korean: "노래 부르자." },
      { english: "Clap your hands!", pron: "클랩 유어 핸즈!", korean: "박수 쳐봐!" },
      { english: "You sing so well!", pron: "유 씽 쏘 웰!", korean: "노래 정말 잘한다!" },
    ] },
  { theme: "영상 시간", tip: "시청 시간을 정할 때 부드럽게 안내해보세요.",
    sentences: [
      { english: "One more show, then we stop.", pron: "원 모어 쇼, 덴 위 스탑.", korean: "한 편만 더 보고 끝이야." },
      { english: "Time to turn it off.", pron: "타임 투 턴 잇 오프.", korean: "이제 끌 시간이야." },
      { english: "Let's do something else.", pron: "렛츠 두 썸씽 엘스.", korean: "다른 거 하자." },
    ] },
  { theme: "정리정돈", tip: "놀이 후 정리 습관을 만들 때 써보세요.",
    sentences: [
      { english: "Let's clean up together.", pron: "렛츠 클린 업 투게더.", korean: "같이 정리하자." },
      { english: "Put the toys away.", pron: "풋 더 토이즈 어웨이.", korean: "장난감 치우자." },
      { english: "Great job cleaning up!", pron: "그레잇 잡 클리닝 업!", korean: "정리 잘했어!" },
    ] },
  { theme: "마트 장보기", tip: "물건을 함께 고르며 이름을 알려주세요.",
    sentences: [
      { english: "Let's go grocery shopping.", pron: "렛츠 고 그로서리 쇼핑.", korean: "장 보러 가자." },
      { english: "Can you find the apples?", pron: "캔 유 파인드 디 애플즈?", korean: "사과 찾을 수 있어?" },
      { english: "Put it in the cart.", pron: "풋 잇 인 더 카트.", korean: "카트에 담자." },
    ] },
  { theme: "계산·기다리기", tip: "계산대에서 차례를 기다리며 써보세요.",
    sentences: [
      { english: "Let's wait in line.", pron: "렛츠 웨잇 인 라인.", korean: "줄 서서 기다리자." },
      { english: "It's our turn now.", pron: "잇츠 아워 턴 나우.", korean: "이제 우리 차례야." },
      { english: "Say thank you.", pron: "세이 땡큐.", korean: "고맙다고 인사하자." },
    ] },
  { theme: "식당에서", tip: "메뉴를 고르며 대화해보세요.",
    sentences: [
      { english: "What do you want to eat?", pron: "왓 두 유 원트 투 잇?", korean: "뭐 먹고 싶어?" },
      { english: "Let's use a spoon.", pron: "렛츠 유즈 어 스푼.", korean: "숟가락으로 먹자." },
      { english: "Be careful, it's hot.", pron: "비 케어풀, 잇츠 핫.", korean: "조심해, 뜨거워." },
    ] },
  { theme: "카페에서", tip: "간단한 주문 상황에서 써보세요.",
    sentences: [
      { english: "Let's find a seat.", pron: "렛츠 파인드 어 씻.", korean: "자리 찾자." },
      { english: "Sit down, please.", pron: "씻 다운, 플리즈.", korean: "앉자." },
      { english: "Use your inside voice.", pron: "유즈 유어 인사이드 보이스.", korean: "작은 목소리로 말하자." },
    ] },
  { theme: "산책·바깥 나들이", tip: "손을 잡고 걸으며 보이는 것들을 이야기해보세요.",
    sentences: [
      { english: "Let's go for a walk.", pron: "렛츠 고 포 어 워크.", korean: "산책하러 가자." },
      { english: "Hold my hand.", pron: "홀드 마이 핸드.", korean: "손 잡아." },
      { english: "Look at that!", pron: "룩 앳 댓!", korean: "저것 좀 봐!" },
    ] },
  { theme: "놀이터", tip: "안전을 챙기며 신나게 말해주세요.",
    sentences: [
      { english: "Do you want to go on the slide?", pron: "두 유 원트 투 고 온 더 슬라이드?", korean: "미끄럼틀 탈래?" },
      { english: "Hold on tight!", pron: "홀드 온 타잇!", korean: "꽉 잡아!" },
      { english: "Be careful, okay?", pron: "비 케어풀, 오케이?", korean: "조심해, 알았지?" },
    ] },
  { theme: "횡단보도·안전", tip: "길을 건널 때 규칙을 함께 말해보세요.",
    sentences: [
      { english: "Stop and look both ways.", pron: "스탑 앤 룩 보쓰 웨이즈.", korean: "멈춰서 양쪽을 봐." },
      { english: "Wait for the green light.", pron: "웨잇 포 더 그린 라잇.", korean: "초록불 기다리자." },
      { english: "Now we can go.", pron: "나우 위 캔 고.", korean: "이제 건너도 돼." },
    ] },
  { theme: "자동차·카시트", tip: "차를 탈 때 안전벨트 습관과 함께 말해주세요.",
    sentences: [
      { english: "Let's get in the car.", pron: "렛츠 겟 인 더 카.", korean: "차에 타자." },
      { english: "Buckle up!", pron: "버클 업!", korean: "안전벨트 매자!" },
      { english: "We're almost there.", pron: "위어 올모스트 데어.", korean: "거의 다 왔어." },
    ] },
  { theme: "대중교통", tip: "버스나 지하철을 탈 때 써보세요.",
    sentences: [
      { english: "Let's take the bus.", pron: "렛츠 테이크 더 버스.", korean: "버스 타자." },
      { english: "Hold on to me.", pron: "홀드 온 투 미.", korean: "나 꼭 잡아." },
      { english: "This is our stop.", pron: "디스 이즈 아워 스탑.", korean: "여기서 내리는 거야." },
    ] },
  { theme: "병원 진료", tip: "무섭지 않게 다정한 톤으로 안심시켜 주세요.",
    sentences: [
      { english: "The doctor will help you.", pron: "더 닥터 윌 헬프 유.", korean: "의사 선생님이 도와줄 거야." },
      { english: "It's okay, I'm right here.", pron: "잇츠 오케이, 아임 라잇 히어.", korean: "괜찮아, 엄마 여기 있어." },
      { english: "You were so brave!", pron: "유 워 쏘 브레이브!", korean: "정말 용감했어!" },
    ] },
  { theme: "약 먹기", tip: "약을 먹일 때 부드럽게 격려해주세요.",
    sentences: [
      { english: "Time to take your medicine.", pron: "타임 투 테이크 유어 메디슨.", korean: "약 먹을 시간이야." },
      { english: "Just a little bit.", pron: "저스트 어 리틀 빗.", korean: "조금만 먹으면 돼." },
      { english: "All done, good job!", pron: "올 던, 굿 잡!", korean: "다 먹었어, 잘했어!" },
    ] },
  { theme: "다쳤을 때", tip: "먼저 감정을 읽어주고 안심시켜 주세요.",
    sentences: [
      { english: "Are you okay?", pron: "아 유 오케이?", korean: "괜찮아?" },
      { english: "Where does it hurt?", pron: "웨어 더즈 잇 허트?", korean: "어디가 아파?" },
      { english: "Let me kiss it better.", pron: "렛 미 키스 잇 베터.", korean: "호 해줄게, 나아져라." },
    ] },
  { theme: "날씨 - 더운 날", tip: "더운 날 나가기 전에 써보세요.",
    sentences: [
      { english: "It's so hot today.", pron: "잇츠 쏘 핫 투데이.", korean: "오늘 너무 덥다." },
      { english: "Let's wear a hat.", pron: "렛츠 웨어 어 햇.", korean: "모자 쓰자." },
      { english: "Drink lots of water.", pron: "드링크 랏츠 오브 워터.", korean: "물 많이 마시자." },
    ] },
  { theme: "날씨 - 추운 날", tip: "추운 날 옷을 입히며 써보세요.",
    sentences: [
      { english: "It's cold outside.", pron: "잇츠 콜드 아웃사이드.", korean: "밖이 춥다." },
      { english: "Let's put on your coat.", pron: "렛츠 풋 온 유어 코트.", korean: "외투 입자." },
      { english: "Keep warm, okay?", pron: "킵 웜, 오케이?", korean: "따뜻하게 있자, 알았지?" },
    ] },
  { theme: "비 오는 날", tip: "비 오는 날 창밖을 보며 말해보세요.",
    sentences: [
      { english: "It's raining outside.", pron: "잇츠 레이닝 아웃사이드.", korean: "밖에 비가 와." },
      { english: "Let's take an umbrella.", pron: "렛츠 테이크 언 엄브렐라.", korean: "우산 가져가자." },
      { english: "Watch out for puddles!", pron: "왓치 아웃 포 퍼들즈!", korean: "웅덩이 조심해!" },
    ] },
  { theme: "감정 - 기쁨", tip: "아이가 웃을 때 함께 표현해보세요.",
    sentences: [
      { english: "You look so happy!", pron: "유 룩 쏘 해피!", korean: "정말 행복해 보인다!" },
      { english: "That makes me happy too.", pron: "댓 메익스 미 해피 투.", korean: "엄마도 기뻐." },
      { english: "Let's celebrate!", pron: "렛츠 셀러브레이트!", korean: "축하하자!" },
    ] },
  { theme: "감정 - 속상함", tip: "아이 감정을 먼저 읽어주는 말이에요.",
    sentences: [
      { english: "Are you feeling sad?", pron: "아 유 필링 새드?", korean: "속상해?" },
      { english: "It's okay to cry.", pron: "잇츠 오케이 투 크라이.", korean: "울어도 괜찮아." },
      { english: "I'm here for you.", pron: "아임 히어 포 유.", korean: "엄마가 옆에 있어." },
    ] },
  { theme: "감정 - 무서움", tip: "무서워할 때 곁에서 안심시켜 주세요.",
    sentences: [
      { english: "Are you scared?", pron: "아 유 스케어드?", korean: "무서워?" },
      { english: "Don't worry, I've got you.", pron: "돈 워리, 아이브 갓 유.", korean: "걱정 마, 엄마가 있잖아." },
      { english: "You're safe with me.", pron: "유어 세이프 위드 미.", korean: "엄마랑 있으면 안전해." },
    ] },
  { theme: "화 다스리기", tip: "감정을 진정시킬 때 천천히 말해주세요.",
    sentences: [
      { english: "Are you angry?", pron: "아 유 앵그리?", korean: "화났어?" },
      { english: "Let's take a deep breath.", pron: "렛츠 테이크 어 딥 브레쓰.", korean: "숨 크게 쉬어보자." },
      { english: "It's okay, calm down.", pron: "잇츠 오케이, 캄 다운.", korean: "괜찮아, 진정하자." },
    ] },
  { theme: "칭찬하기", tip: "작은 성취에도 아낌없이 칭찬해주세요.",
    sentences: [
      { english: "Good job, sweetie!", pron: "굿 잡, 스위티!", korean: "잘했어, 아가!" },
      { english: "I'm so proud of you.", pron: "아임 쏘 프라우드 오브 유.", korean: "네가 정말 자랑스러워." },
      { english: "You did it all by yourself!", pron: "유 디드 잇 올 바이 유어셀프!", korean: "혼자서 다 해냈네!" },
    ] },
  { theme: "감사 인사", tip: "고마움을 표현하는 습관을 길러주세요.",
    sentences: [
      { english: "Thank you so much.", pron: "땡큐 쏘 머치.", korean: "정말 고마워." },
      { english: "You're welcome.", pron: "유어 웰컴.", korean: "천만에." },
      { english: "Can you say thank you?", pron: "캔 유 세이 땡큐?", korean: "고맙다고 말할 수 있어?" },
    ] },
  { theme: "사과하기", tip: "실수했을 때 사과하는 법을 알려주세요.",
    sentences: [
      { english: "I'm sorry.", pron: "아임 쏘리.", korean: "미안해." },
      { english: "It's okay, I forgive you.", pron: "잇츠 오케이, 아이 포기브 유.", korean: "괜찮아, 용서할게." },
      { english: "Let's say sorry together.", pron: "렛츠 세이 쏘리 투게더.", korean: "같이 미안하다고 하자." },
    ] },
  { theme: "부탁·예절", tip: "부탁할 때 예의 표현을 자연스럽게 알려주세요.",
    sentences: [
      { english: "Can you say please?", pron: "캔 유 세이 플리즈?", korean: "'please'라고 말해볼래?" },
      { english: "May I have some more?", pron: "메이 아이 해브 썸 모어?", korean: "더 먹어도 될까요?" },
      { english: "That's so polite!", pron: "댓츠 쏘 폴라잇!", korean: "정말 예의 바르구나!" },
    ] },
  { theme: "친구와 나누기", tip: "장난감을 나눠 쓸 때 알려주세요.",
    sentences: [
      { english: "Let's share with your friend.", pron: "렛츠 쉐어 위드 유어 프렌드.", korean: "친구랑 나눠 쓰자." },
      { english: "Sharing is caring.", pron: "쉐어링 이즈 케어링.", korean: "나누는 건 배려하는 거야." },
      { english: "You're such a good friend.", pron: "유어 서치 어 굿 프렌드.", korean: "너 정말 좋은 친구구나." },
    ] },
  { theme: "차례 지키기", tip: "순서를 기다릴 때 써보세요.",
    sentences: [
      { english: "Let's take turns.", pron: "렛츠 테이크 턴즈.", korean: "번갈아 하자." },
      { english: "It's your turn now.", pron: "잇츠 유어 턴 나우.", korean: "이제 네 차례야." },
      { english: "Wait for your turn.", pron: "웨잇 포 유어 턴.", korean: "차례를 기다리자." },
    ] },
  { theme: "기다리기", tip: "기다리는 상황을 놀이처럼 만들어보세요.",
    sentences: [
      { english: "Let's wait a little.", pron: "렛츠 웨잇 어 리틀.", korean: "조금만 기다리자." },
      { english: "Almost ready.", pron: "올모스트 레디.", korean: "거의 다 됐어." },
      { english: "Thank you for waiting.", pron: "땡큐 포 웨이팅.", korean: "기다려줘서 고마워." },
    ] },
  { theme: "도와주기", tip: "함께 하는 일에서 협동을 알려주세요.",
    sentences: [
      { english: "Can you help me?", pron: "캔 유 헬프 미?", korean: "엄마 좀 도와줄래?" },
      { english: "Let's do it together.", pron: "렛츠 두 잇 투게더.", korean: "같이 하자." },
      { english: "Thank you for helping.", pron: "땡큐 포 헬핑.", korean: "도와줘서 고마워." },
    ] },
  { theme: "목욕 시간", tip: "물놀이하듯 즐겁게 말해주세요.",
    sentences: [
      { english: "It's bath time!", pron: "잇츠 배쓰 타임!", korean: "목욕 시간이야!" },
      { english: "The water is warm.", pron: "더 워터 이즈 웜.", korean: "물이 따뜻해." },
      { english: "Let's wash your hair.", pron: "렛츠 워시 유어 헤어.", korean: "머리 감자." },
    ] },
  { theme: "잠자리 준비", tip: "잠자기 전 차분한 루틴으로 써보세요.",
    sentences: [
      { english: "Let's put on your pajamas.", pron: "렛츠 풋 온 유어 파자마즈.", korean: "잠옷 입자." },
      { english: "It's almost bedtime.", pron: "잇츠 올모스트 베드타임.", korean: "잘 시간 다 됐어." },
      { english: "Let's read one story.", pron: "렛츠 리드 원 스토리.", korean: "책 한 권 읽자." },
    ] },
  { theme: "잘 자 인사", tip: "매일 밤 같은 말로 마무리하면 안정감을 줘요.",
    sentences: [
      { english: "Good night, sleep tight.", pron: "굿나잇, 슬립 타잇.", korean: "잘 자, 좋은 꿈 꿔." },
      { english: "Sweet dreams.", pron: "스윗 드림즈.", korean: "좋은 꿈 꿔." },
      { english: "I love you so much.", pron: "아이 러브 유 쏘 머치.", korean: "정말 많이 사랑해." },
    ] },
  { theme: "전화 통화", tip: "가족과 통화할 때 인사말을 알려주세요.",
    sentences: [
      { english: "Say hi to Grandma.", pron: "세이 하이 투 그랜마.", korean: "할머니한테 인사하자." },
      { english: "How are you?", pron: "하우 아 유?", korean: "잘 지내세요?" },
      { english: "I love you, bye!", pron: "아이 러브 유, 바이!", korean: "사랑해요, 안녕!" },
    ] },
  { theme: "사진 찍기", tip: "사진 찍을 때 즐겁게 웃으며 써보세요.",
    sentences: [
      { english: "Let's take a picture.", pron: "렛츠 테이크 어 픽쳐.", korean: "사진 찍자." },
      { english: "Say cheese!", pron: "세이 치즈!", korean: "치즈~ 하자!" },
      { english: "What a great smile!", pron: "왓 어 그레잇 스마일!", korean: "정말 예쁜 미소다!" },
    ] },
  { theme: "생일·축하", tip: "축하하는 자리에서 함께 써보세요.",
    sentences: [
      { english: "Happy birthday to you!", pron: "해피 벌스데이 투 유!", korean: "생일 축하해!" },
      { english: "Let's make a wish.", pron: "렛츠 메이크 어 위시.", korean: "소원 빌자." },
      { english: "Blow out the candles!", pron: "블로우 아웃 더 캔들즈!", korean: "촛불 끄자!" },
    ] },
  { theme: "위로하기", tip: "아이가 힘들어할 때 따뜻하게 안아주며 말해주세요.",
    sentences: [
      { english: "It's going to be okay.", pron: "잇츠 고잉 투 비 오케이.", korean: "다 괜찮아질 거야." },
      { english: "Do you want a hug?", pron: "두 유 원트 어 허그?", korean: "안아줄까?" },
      { english: "I'm always here for you.", pron: "아임 올웨이즈 히어 포 유.", korean: "엄마는 항상 네 곁에 있어." },
    ] },
  { theme: "배변 훈련", tip: "배변 훈련 중일 때 다정하게 격려해주세요.",
    sentences: [
      { english: "Do you need to go potty?", pron: "두 유 니드 투 고 파티?", korean: "화장실 가고 싶어?" },
      { english: "Let's go to the bathroom.", pron: "렛츠 고 투 더 배쓰룸.", korean: "화장실 가자." },
      { english: "Great job!", pron: "그레잇 잡!", korean: "정말 잘했어!" },
    ] },
  { theme: "외출 준비", tip: "나가기 전 준비 과정에서 하나씩 말해주세요.",
    sentences: [
      { english: "Let's get ready.", pron: "렛츠 겟 레디.", korean: "준비하자." },
      { english: "Put on your jacket.", pron: "풋 온 유어 재킷.", korean: "겉옷 입자." },
      { english: "Are you ready to go?", pron: "아 유 레디 투 고?", korean: "나갈 준비 됐어?" },
    ] },
  { theme: "숫자 세기", tip: "계단을 오르내릴 때 같이 세어보세요.",
    sentences: [
      { english: "Let's count together.", pron: "렛츠 카운트 투게더.", korean: "같이 세어보자." },
      { english: "One, two, three!", pron: "원, 투, 쓰리!", korean: "하나, 둘, 셋!" },
      { english: "How many are there?", pron: "하우 매니 아 데어?", korean: "몇 개 있어?" },
    ] },
  { theme: "색깔 배우기", tip: "주변 물건 색을 가리키며 물어보세요.",
    sentences: [
      { english: "What color is this?", pron: "왓 컬러 이즈 디스?", korean: "이건 무슨 색이야?" },
      { english: "The sky is blue.", pron: "더 스카이 이즈 블루.", korean: "하늘은 파란색이야." },
      { english: "Can you find something red?", pron: "캔 유 파인드 썸씽 레드?", korean: "빨간 거 찾을 수 있어?" },
    ] },
  { theme: "동물 이름", tip: "동물을 보거나 그림책에서 이름을 알려주세요.",
    sentences: [
      { english: "Look, it's a puppy!", pron: "룩, 잇츠 어 퍼피!", korean: "봐봐, 강아지야!" },
      { english: "What sound does a cat make?", pron: "왓 사운드 더즈 어 캣 메이크?", korean: "고양이는 어떤 소리를 내지?" },
      { english: "The cow says moo.", pron: "더 카우 세즈 무.", korean: "소는 음메 하고 울어." },
    ] },
  { theme: "음식 이름", tip: "밥 먹을 때 음식 이름을 자연스럽게 알려주세요.",
    sentences: [
      { english: "Do you like apples?", pron: "두 유 라익 애플즈?", korean: "사과 좋아해?" },
      { english: "This is rice.", pron: "디스 이즈 라이스.", korean: "이건 밥이야." },
      { english: "Let's try one bite.", pron: "렛츠 트라이 원 바이트.", korean: "한 입만 먹어보자." },
    ] },
  { theme: "몸 부위", tip: "몸을 만지며 이름을 말해주세요.",
    sentences: [
      { english: "Where is your nose?", pron: "웨어 이즈 유어 노즈?", korean: "코가 어디 있어?" },
      { english: "Touch your toes.", pron: "터치 유어 토우즈.", korean: "발가락 만져봐." },
      { english: "These are your hands.", pron: "디즈 아 유어 핸즈.", korean: "이건 네 손이야." },
    ] },
  { theme: "하루 마무리", tip: "하루를 마무리하며 오늘을 함께 돌아보세요.",
    sentences: [
      { english: "What a fun day!", pron: "왓 어 펀 데이!", korean: "정말 재미있는 하루였어!" },
      { english: "I love spending time with you.", pron: "아이 러브 스펜딩 타임 위드 유.", korean: "너랑 함께하는 시간이 좋아." },
      { english: "See you in the morning!", pron: "씨 유 인 더 모닝!", korean: "내일 아침에 보자!" },
    ] },
];

export default sentences;
