// 3세(만 3세 전후) 아이와의 일상 영어 대화를 위한 문장 DB
// 하루에 3문장씩, 날짜(연중 일수) 기준으로 순환 사용됩니다.
// 새 세트를 배열 뒤에 추가하면 자동으로 순환 주기에 포함됩니다.

const sentences = [
  { theme: "아침 인사", tip: "눈뜨자마자 매일 같은 말로 인사해주면 아이가 자연스럽게 따라 해요.",
    sentences: [
      { english: "Good morning!", korean: "좋은 아침이에요!" },
      { english: "Did you sleep well?", korean: "잘 잤어요?" },
      { english: "Let's get up now.", korean: "이제 일어나요." },
    ] },
  { theme: "아침밥", tip: "밥 먹기 전후로 반복해서 말해주세요.",
    sentences: [
      { english: "Let's eat breakfast.", korean: "아침 먹자." },
      { english: "I'm hungry.", korean: "나 배고파." },
      { english: "This is yummy!", korean: "이거 맛있어!" },
    ] },
  { theme: "양치질", tip: "칫솔질하는 동안 신나게 말해주면 좋아해요.",
    sentences: [
      { english: "Brush your teeth.", korean: "이 닦자." },
      { english: "Open your mouth.", korean: "입 벌려봐." },
      { english: "Good job, all done!", korean: "잘했어, 다 했다!" },
    ] },
  { theme: "옷 입기", tip: "옷을 고를 때 선택지를 주며 말해보세요.",
    sentences: [
      { english: "Let's get dressed.", korean: "옷 입자." },
      { english: "Put on your shirt.", korean: "셔츠 입어봐." },
      { english: "You look so cute!", korean: "너 정말 귀엽다!" },
    ] },
  { theme: "신발 신기", tip: "현관에서 나갈 준비할 때 쓰기 좋아요.",
    sentences: [
      { english: "Put on your shoes.", korean: "신발 신자." },
      { english: "Which shoes do you like?", korean: "어떤 신발이 좋아?" },
      { english: "Let's go outside!", korean: "밖에 나가자!" },
    ] },
  { theme: "놀이터", tip: "놀이터에서 신나는 톤으로 말해주세요.",
    sentences: [
      { english: "Let's go to the playground.", korean: "놀이터에 가자." },
      { english: "I want to swing.", korean: "나 그네 타고 싶어." },
      { english: "Be careful, okay?", korean: "조심해, 알았지?" },
    ] },
  { theme: "공놀이", tip: "공을 주고받으며 말해보세요.",
    sentences: [
      { english: "Let's play with the ball.", korean: "공 가지고 놀자." },
      { english: "Catch the ball!", korean: "공 잡아!" },
      { english: "Nice throw!", korean: "잘 던졌어!" },
    ] },
  { theme: "색깔", tip: "주변 물건 색을 가리키며 질문해보세요.",
    sentences: [
      { english: "What color is this?", korean: "이건 무슨 색이야?" },
      { english: "I like the color red.", korean: "나는 빨간색이 좋아." },
      { english: "The sky is blue.", korean: "하늘은 파란색이야." },
    ] },
  { theme: "숫자 세기", tip: "계단을 오르내릴 때 같이 세어보세요.",
    sentences: [
      { english: "Let's count together.", korean: "같이 세어보자." },
      { english: "One, two, three!", korean: "하나, 둘, 셋!" },
      { english: "How many do you see?", korean: "몇 개 보여?" },
    ] },
  { theme: "동물 - 강아지", tip: "강아지를 보면 손가락으로 가리키며 말해보세요.",
    sentences: [
      { english: "Look, a dog!", korean: "봐봐, 강아지야!" },
      { english: "The dog is cute.", korean: "강아지가 귀여워." },
      { english: "Woof woof, says the dog.", korean: "멍멍, 강아지가 그래." },
    ] },
  { theme: "동물 - 고양이", tip: "동물 소리를 흉내 내며 말하면 더 재밌어해요.",
    sentences: [
      { english: "The cat is sleeping.", korean: "고양이가 자고 있어." },
      { english: "Can I pet the cat?", korean: "고양이 만져도 돼?" },
      { english: "Meow, says the cat.", korean: "야옹, 고양이가 그래." },
    ] },
  { theme: "날씨 - 맑음", tip: "창밖을 보며 오늘의 날씨를 이야기해보세요.",
    sentences: [
      { english: "It's sunny today.", korean: "오늘 날씨가 맑아." },
      { english: "Let's wear a hat.", korean: "모자 쓰자." },
      { english: "The sun is bright.", korean: "해가 밝아." },
    ] },
  { theme: "날씨 - 비", tip: "비 오는 날 창밖을 보며 말해보세요.",
    sentences: [
      { english: "It's raining outside.", korean: "밖에 비가 와." },
      { english: "Let's take an umbrella.", korean: "우산 가져가자." },
      { english: "I love rainy days.", korean: "나는 비 오는 날이 좋아." },
    ] },
  { theme: "목욕 시간", tip: "물놀이하듯 즐겁게 말해주세요.",
    sentences: [
      { english: "It's bath time!", korean: "목욕 시간이야!" },
      { english: "The water feels warm.", korean: "물이 따뜻해." },
      { english: "Let's wash your hair.", korean: "머리 감자." },
    ] },
  { theme: "손 씻기", tip: "밥 먹기 전, 외출 후에 반복해주세요.",
    sentences: [
      { english: "Wash your hands, please.", korean: "손 씻어줘." },
      { english: "Use soap and water.", korean: "비누랑 물을 써." },
      { english: "Now your hands are clean.", korean: "이제 손이 깨끗해." },
    ] },
  { theme: "정리하기", tip: "놀이 후 정리 습관을 만들 때 써보세요.",
    sentences: [
      { english: "Let's clean up the toys.", korean: "장난감 정리하자." },
      { english: "Put it back, please.", korean: "제자리에 놓아줘." },
      { english: "Great job cleaning up!", korean: "정리 잘했어!" },
    ] },
  { theme: "감정 - 행복", tip: "아이가 웃을 때 함께 말해보세요.",
    sentences: [
      { english: "I am happy!", korean: "나는 행복해!" },
      { english: "You make me smile.", korean: "너 때문에 웃음이 나." },
      { english: "Let's do a happy dance!", korean: "신나는 춤 추자!" },
    ] },
  { theme: "감정 - 슬픔", tip: "아이 감정을 먼저 읽어주는 말이에요.",
    sentences: [
      { english: "Are you sad?", korean: "슬퍼?" },
      { english: "It's okay to cry.", korean: "울어도 괜찮아." },
      { english: "I'm here for you.", korean: "내가 옆에 있을게." },
    ] },
  { theme: "감정 - 화남", tip: "감정을 진정시킬 때 천천히 말해주세요.",
    sentences: [
      { english: "Are you angry?", korean: "화났어?" },
      { english: "Let's take a deep breath.", korean: "숨 크게 쉬어보자." },
      { english: "It's okay, calm down.", korean: "괜찮아, 진정해." },
    ] },
  { theme: "가족 - 엄마", tip: "엄마와의 애착 표현에 좋아요.",
    sentences: [
      { english: "I love you, Mom.", korean: "엄마 사랑해요." },
      { english: "Where is Mommy?", korean: "엄마 어디 있어?" },
      { english: "Mommy, hug me please.", korean: "엄마, 안아줘." },
    ] },
  { theme: "가족 - 아빠", tip: "아빠가 퇴근했을 때 써보세요.",
    sentences: [
      { english: "I love you, Dad.", korean: "아빠 사랑해요." },
      { english: "Daddy is home!", korean: "아빠 왔다!" },
      { english: "Let's play with Daddy.", korean: "아빠랑 놀자." },
    ] },
  { theme: "낮잠 시간", tip: "낮잠 전 루틴으로 사용해보세요.",
    sentences: [
      { english: "It's nap time.", korean: "낮잠 잘 시간이야." },
      { english: "Let's lie down.", korean: "누워보자." },
      { english: "Sweet dreams, sleepy head.", korean: "좋은 꿈 꿔, 잠꾸러기." },
    ] },
  { theme: "잠자리 인사", tip: "매일 밤 같은 순서로 말해주면 안정감을 줘요.",
    sentences: [
      { english: "It's time for bed.", korean: "잘 시간이야." },
      { english: "Good night, sleep tight.", korean: "잘 자, 좋은 꿈 꿔." },
      { english: "I love you so much.", korean: "정말 많이 사랑해." },
    ] },
  { theme: "그림책 읽기", tip: "책장을 넘기며 질문해보세요.",
    sentences: [
      { english: "Let's read a book.", korean: "책 읽자." },
      { english: "Turn the page, please.", korean: "페이지 넘겨줘." },
      { english: "What happens next?", korean: "다음에 무슨 일이 생길까?" },
    ] },
  { theme: "노래 부르기", tip: "좋아하는 동요를 같이 불러보세요.",
    sentences: [
      { english: "Let's sing a song.", korean: "노래 부르자." },
      { english: "Sing it with me.", korean: "나랑 같이 불러." },
      { english: "That was a great song!", korean: "노래 정말 좋았어!" },
    ] },
  { theme: "간식 시간", tip: "간식 고를 때 선택권을 주며 말해보세요.",
    sentences: [
      { english: "It's snack time.", korean: "간식 시간이야." },
      { english: "Do you want a cookie?", korean: "쿠키 먹을래?" },
      { english: "This snack is tasty.", korean: "이 간식 맛있어." },
    ] },
  { theme: "물 마시기", tip: "물을 자주 챙겨줄 때 써보세요.",
    sentences: [
      { english: "Drink some water.", korean: "물 좀 마셔." },
      { english: "Are you thirsty?", korean: "목마르니?" },
      { english: "Here's your cup.", korean: "여기 컵 있어." },
    ] },
  { theme: "과일", tip: "과일을 먹으며 이름을 알려주세요.",
    sentences: [
      { english: "I like apples.", korean: "나는 사과가 좋아." },
      { english: "This banana is sweet.", korean: "이 바나나는 달아." },
      { english: "Do you want grapes?", korean: "포도 먹을래?" },
    ] },
  { theme: "야채", tip: "야채를 잘 먹었을 때 칭찬해주세요.",
    sentences: [
      { english: "Eat your carrots.", korean: "당근 먹어." },
      { english: "Vegetables are good for you.", korean: "야채는 몸에 좋아." },
      { english: "Try one more bite.", korean: "한 입만 더 먹어봐." },
    ] },
  { theme: "사랑 표현", tip: "이유 없이 자주 말해주면 좋아요.",
    sentences: [
      { english: "I love you very much.", korean: "너를 정말 많이 사랑해." },
      { english: "You are my sunshine.", korean: "너는 나의 햇살이야." },
      { english: "Give me a hug.", korean: "안아줘." },
    ] },
  { theme: "칭찬하기", tip: "작은 성취에도 아낌없이 칭찬해주세요.",
    sentences: [
      { english: "Good job, sweetie!", korean: "잘했어, 아가!" },
      { english: "I'm so proud of you.", korean: "네가 정말 자랑스러워." },
      { english: "You did it!", korean: "네가 해냈어!" },
    ] },
  { theme: "도와주세요", tip: "도움을 요청하는 표현을 알려줄 때 써보세요.",
    sentences: [
      { english: "Can you help me?", korean: "나 도와줄 수 있어?" },
      { english: "I need your help.", korean: "네 도움이 필요해." },
      { english: "Thank you for helping.", korean: "도와줘서 고마워." },
    ] },
  { theme: "부탁 표현", tip: "부탁할 때 예의 표현을 자연스럽게 알려주세요.",
    sentences: [
      { english: "Please, may I have this?", korean: "이거 가져도 될까요?" },
      { english: "Say please.", korean: "'please'라고 말해봐." },
      { english: "Please and thank you.", korean: "부탁해요, 그리고 고마워요." },
    ] },
  { theme: "감사 표현", tip: "고마움을 표현하는 습관을 길러주세요.",
    sentences: [
      { english: "Thank you so much.", korean: "정말 고마워." },
      { english: "You're welcome.", korean: "천만에." },
      { english: "Say thank you.", korean: "고맙다고 말해봐." },
    ] },
  { theme: "사과 표현", tip: "실수했을 때 사과하는 법을 알려주세요.",
    sentences: [
      { english: "I'm sorry.", korean: "미안해." },
      { english: "It's okay, I forgive you.", korean: "괜찮아, 용서할게." },
      { english: "Let's say sorry together.", korean: "같이 미안하다고 말하자." },
    ] },
  { theme: "몸 부위", tip: "몸을 만지며 이름을 말해주세요.",
    sentences: [
      { english: "Where is your nose?", korean: "코가 어디 있어?" },
      { english: "Touch your toes.", korean: "발가락 만져봐." },
      { english: "This is my hand.", korean: "이건 내 손이야." },
    ] },
  { theme: "얼굴", tip: "거울을 보며 표정을 이야기해보세요.",
    sentences: [
      { english: "You have a happy face.", korean: "너 행복한 얼굴이네." },
      { english: "Look at your eyes.", korean: "눈을 봐봐." },
      { english: "Smile for me!", korean: "나를 위해 웃어줘!" },
    ] },
  { theme: "산책하기", tip: "손을 잡고 걸으며 말해보세요.",
    sentences: [
      { english: "Let's take a walk.", korean: "산책하자." },
      { english: "Hold my hand.", korean: "내 손 잡아." },
      { english: "Look at the trees.", korean: "나무를 봐봐." },
    ] },
  { theme: "자동차", tip: "차를 탈 때 안전벨트 습관과 함께 말해주세요.",
    sentences: [
      { english: "Let's get in the car.", korean: "차에 타자." },
      { english: "Buckle your seatbelt.", korean: "안전벨트 매자." },
      { english: "We are going home.", korean: "우리 집에 가고 있어." },
    ] },
  { theme: "공원 나들이", tip: "공원에서 보이는 것들을 함께 이야기해보세요.",
    sentences: [
      { english: "Let's go to the park.", korean: "공원에 가자." },
      { english: "I see a duck!", korean: "오리가 보여!" },
      { english: "Let's feed the ducks.", korean: "오리한테 먹이 주자." },
    ] },
  { theme: "친구와 놀기", tip: "친구를 만났을 때 쓰기 좋은 표현이에요.",
    sentences: [
      { english: "Let's play with friends.", korean: "친구들이랑 놀자." },
      { english: "Can I join you?", korean: "나도 같이 해도 돼?" },
      { english: "We are having fun!", korean: "우리 재밌게 놀고 있어!" },
    ] },
  { theme: "나누기", tip: "장난감을 나눠 쓸 때 알려주세요.",
    sentences: [
      { english: "Let's share the toy.", korean: "장난감 같이 쓰자." },
      { english: "Can I have a turn?", korean: "나도 한 번 해도 돼?" },
      { english: "Sharing is caring.", korean: "나누는 건 배려하는 거야." },
    ] },
  { theme: "장난감", tip: "좋아하는 장난감 이름을 물어보세요.",
    sentences: [
      { english: "This is my favorite toy.", korean: "이건 내가 제일 좋아하는 장난감이야." },
      { english: "Let's play with blocks.", korean: "블록 가지고 놀자." },
      { english: "Where is your teddy bear?", korean: "네 곰인형 어디 있어?" },
    ] },
  { theme: "그림 그리기", tip: "그림 그릴 때 색을 물어보며 대화해보세요.",
    sentences: [
      { english: "Let's draw a picture.", korean: "그림 그리자." },
      { english: "What color do you want?", korean: "무슨 색 원해?" },
      { english: "That's a beautiful drawing!", korean: "정말 예쁜 그림이야!" },
    ] },
  { theme: "블록 놀이", tip: "블록을 쌓고 무너뜨리며 놀아보세요.",
    sentences: [
      { english: "Let's build a tower.", korean: "탑을 만들자." },
      { english: "Stack the blocks up.", korean: "블록을 쌓아보자." },
      { english: "Oh no, it fell down!", korean: "어머, 무너졌다!" },
    ] },
  { theme: "퍼즐", tip: "퍼즐 조각을 맞추며 격려해주세요.",
    sentences: [
      { english: "Let's do a puzzle.", korean: "퍼즐 하자." },
      { english: "Where does this piece go?", korean: "이 조각 어디로 가?" },
      { english: "You finished the puzzle!", korean: "퍼즐 다 했어!" },
    ] },
  { theme: "크기 비교", tip: "물건 크기를 비교하며 말해보세요.",
    sentences: [
      { english: "This one is big.", korean: "이건 커." },
      { english: "This one is small.", korean: "이건 작아." },
      { english: "Which one is bigger?", korean: "어떤 게 더 커?" },
    ] },
  { theme: "모양", tip: "주변 물건에서 모양을 찾아보세요.",
    sentences: [
      { english: "This is a circle.", korean: "이건 동그라미야." },
      { english: "Can you find a square?", korean: "네모 찾을 수 있어?" },
      { english: "That's a triangle.", korean: "그건 세모야." },
    ] },
  { theme: "계절 - 봄", tip: "산책하며 봄 풍경을 이야기해보세요.",
    sentences: [
      { english: "Spring is here!", korean: "봄이 왔어!" },
      { english: "The flowers are blooming.", korean: "꽃이 피고 있어." },
      { english: "Let's smell the flowers.", korean: "꽃 냄새 맡아보자." },
    ] },
  { theme: "계절 - 여름", tip: "더운 날 물놀이와 함께 말해보세요.",
    sentences: [
      { english: "It's hot in summer.", korean: "여름엔 더워." },
      { english: "Let's go swimming.", korean: "수영하러 가자." },
      { english: "I want some ice cream.", korean: "아이스크림 먹고 싶어." },
    ] },
  { theme: "계절 - 가을", tip: "낙엽을 밟으며 말해보세요.",
    sentences: [
      { english: "The leaves are falling.", korean: "낙엽이 떨어지고 있어." },
      { english: "It's getting cooler.", korean: "날씨가 시원해지고 있어." },
      { english: "Let's jump in the leaves.", korean: "낙엽 위에서 점프하자." },
    ] },
  { theme: "계절 - 겨울", tip: "추운 날 옷 입히며 말해보세요.",
    sentences: [
      { english: "It's cold in winter.", korean: "겨울엔 추워." },
      { english: "Let's wear a warm coat.", korean: "따뜻한 외투 입자." },
      { english: "Look, it's snowing!", korean: "봐봐, 눈 온다!" },
    ] },
  { theme: "동물원", tip: "동물원 나들이 전후로 써보세요.",
    sentences: [
      { english: "Let's go to the zoo.", korean: "동물원에 가자." },
      { english: "Look at the elephant!", korean: "코끼리 봐봐!" },
      { english: "The lion is roaring.", korean: "사자가 으르렁대." },
    ] },
  { theme: "바다", tip: "바다 여행 갈 때 써보세요.",
    sentences: [
      { english: "Let's go to the beach.", korean: "바다에 가자." },
      { english: "The waves are big.", korean: "파도가 커." },
      { english: "Let's build a sandcastle.", korean: "모래성 만들자." },
    ] },
  { theme: "음악 듣기", tip: "음악을 틀어놓고 함께 즐겨보세요.",
    sentences: [
      { english: "Let's listen to music.", korean: "음악 듣자." },
      { english: "Do you like this song?", korean: "이 노래 좋아?" },
      { english: "Turn up the volume.", korean: "소리 좀 키워줘." },
    ] },
  { theme: "춤추기", tip: "신나는 노래에 맞춰 함께 춤춰보세요.",
    sentences: [
      { english: "Let's dance together.", korean: "같이 춤추자." },
      { english: "Move your body!", korean: "몸을 움직여봐!" },
      { english: "That was so much fun.", korean: "정말 재미있었어." },
    ] },
  { theme: "인사 - 안녕", tip: "만나고 헤어질 때 손을 흔들며 말해보세요.",
    sentences: [
      { english: "Hello, nice to see you!", korean: "안녕, 만나서 반가워!" },
      { english: "Goodbye, see you later!", korean: "잘 가, 또 보자!" },
      { english: "Wave bye-bye.", korean: "손 흔들어 인사해." },
    ] },
  { theme: "화장실 가기", tip: "배변 훈련 중일 때 다정하게 말해주세요.",
    sentences: [
      { english: "Do you need the potty?", korean: "화장실 가고 싶어?" },
      { english: "Let's go to the bathroom.", korean: "화장실 가자." },
      { english: "Great job going potty!", korean: "화장실 잘 갔다 왔네!" },
    ] },
  { theme: "옷 색깔 고르기", tip: "옷 고를 때 선택권을 주며 말해보세요.",
    sentences: [
      { english: "Which shirt do you want?", korean: "어떤 셔츠 입고 싶어?" },
      { english: "This one is warm.", korean: "이건 따뜻해." },
      { english: "You picked a good one!", korean: "잘 골랐어!" },
    ] },
  { theme: "하루 마무리", tip: "하루를 마무리하며 오늘을 되돌아보세요.",
    sentences: [
      { english: "What a fun day!", korean: "정말 재미있는 하루였어!" },
      { english: "I love spending time with you.", korean: "너랑 시간 보내는 게 좋아." },
      { english: "See you tomorrow!", korean: "내일 보자!" },
    ] },
];

export default sentences;
